#!/usr/bin/env bash
#install the ufw firewall

sudo apt-get update
sudo apt-get install ufw -y
sudo ufw default deny incoming
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
